config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :authors
  resources :books
  resources :users

  controller :sessions do
    get  "/",  :action => :new,     :as => :login
    post "/",  :action => :create,  :as => false
    get  "/logout", :action => :destroy, :as => :logout
  end

  controller :books do
    get "/bought/:id", action: :bought, as: :bought
    get "/find-a-book/", action: :search, as: :books_search
  end

  controller :dashboard do
    get "/welcome", action: :index, as: :dashboard 
  end
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  belongs_to :user

  validates :name, presence: true
  validates :user_id, presence: true
  validates :slug, uniqueness: { scope: :user_id, message: I18n.t('activerecord.errors.author.slug.duplicated') }

  scope :user, -> (user) { where(user_id: user) }
  scope :dashboard, -> { limit(5).order('id DESC') }
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :user

  validates :name, presence: true
  validates :author_id, presence: true
  validates :wishlist, inclusion: [true, false]
  validates :link, presence: true 
  validates :read, inclusion: [true, false]
  validates :user_id, presence: true
  validates :slug, uniqueness: { scope: :user_id, message: I18n.t('activerecord.errors.book.slug.duplicated') }

  scope :user, -> (user) { where(user_id: user) }
  scope :read, -> { where(read: true) }
  scope :bought, -> { where(wishlist: false) }
  scope :wishlist, ->  { where(wishlist: true) }
  scope :dashboard, -> { limit(5).order('id DESC') }

  def self.search(search, user)
    search_condition = "%" + search + "%"
    where(['name LIKE ? AND user_id = ?', search_condition, user])
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authors
  has_many :books

  validates :name, presence: true
  validates :email, presence: true
  validates :login, presence: true
  validates :password, presence: true

  def password=(password)
    value = Digest::SHA1.hexdigest(password)
    write_attribute(:password, value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :is_admin?
  add_flash_types :success

  private
  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
  end

  def require_logged_user
    return if logged_in?
    redirect_to root_path
  end

  def is_admin?
    User.where(id: session[:user_id]).first.permission == 0
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :require_logged_user
  
  def index
    @title = I18n.t('authors.index.title')
  	@authors = Author.where(user_id: @current_user).order(:name)
  end

  def new
    @title = I18n.t('authors.new.title')
  	@author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to authors_path, success: t('authors.create.salvo_sucesso')
    else
      render :new
    end
  end

  def edit
    @title = I18n.t('authors.edit.title')
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      redirect_to authors_path, success: t('authors.update.atualizado_sucesso')
    else
      render :edit
    end 
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
 
    redirect_to authors_path, success: t('authors.destroy.deletado_sucesso')
  end

  private
  def author_params
    params.require(:author).permit(:name).merge!({user_id: session[:user_id], slug: params[:author][:name].parameterize})
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_filter :require_logged_user
  
  def index
    @title = I18n.t('books.index.title')
    @all_books = Book.where(user_id: @current_user).order(name: :desc)
  end

  def new
    @title = I18n.t('books.new.title')
    @book = Book.new
    @authors = Author.where(user_id: @current_user).order(:name)
    gon.nota = 0
    if @authors.empty?
      redirect_to authors_path, alert: t('books.new.aviso') 
    end
  end

  def create
    @book = Book.new(book_params)
    @authors = Author.where(user_id: @current_user).order(:name)

    if @book.save
      redirect_to books_path, success: t('books.create.salvo_sucesso')
    else
      render :new
    end
  end

  def edit
    @title = I18n.t('books.edit.title')
    @book = Book.find(params[:id])
    @authors = Author.where(user_id: @current_user).order(:name)
    gon.nota = @book.grade || 0
  end

  def update
    @book = Book.find(params[:id])
    @authors = Author.where(user_id: @current_user).order(:name)

    if @book.update_attributes(book_params)
      redirect_to books_path, success: t('books.update.atualizado_sucesso')
    else
      render :edit
    end 
  end

  def bought
    @book = Book.find(params[:id])
    @book.wishlist = false

    if @book.save
      redirect_to dashboard_path, success: t('books.atualizado_sucesso')
    else
      redirect_to dashboard_path, failure: t('books.atualizado_falha')
    end
  end

  def search
    @books = Book.search(params[:search], @current_user)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
 
    redirect_to books_path, success: t('books.destroy.deletado_sucesso')
  end

  private
  def book_params
    params.require(:book).permit(:name, :author_id, :grade, :wishlist, :link, :read).merge!({user_id: session[:user_id], slug: params[:book][:name].parameterize})
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_logged_user
  
  def index
    @title = I18n.t('dashboard.index.title')

    @ultimos_adicionados = Book.user(@current_user).wishlist.dashboard
    @ultimos_lidos = Book.user(@current_user).read.dashboard
    @ultimos_autores = Author.user(@current_user).dashboard
    @livros_comprados = Book.user(@current_user).bought.dashboard
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to dashboard_path if logged_in?
  end

  def create
    reset_session

    user = User.find_by_login(params[:login])
    password_encripted = Digest::SHA1.hexdigest(params[:password])

    if user && user.password == password_encripted
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      flash.now[:notice] = I18n.t('sessions.errors.login')
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_logged_user
  
  def index
    @title = I18n.t('users.index.title')
    @users = User.all
  end

  def new
    @title = I18n.t('users.new.title')
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, success: t('users.create.salvo_sucesso')
    else
      render :new
    end
  end

  def edit
    @title = I18n.t('users.edit.title')
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to users_path, success: t('users.update.atualizado_sucesso')
    else
      render :edit
    end 
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path, success: t('users.destroy.deletado_sucesso')
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :login, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def monta_title
    if @title
      "#{I18n.t('geral.app_name')} - #{@title}"
    else
      I18n.t('geral.app_name') 
    end
  end

  def traduz_resultado(resultado, tipo)
    I18n.t("geral.#{tipo}.#{resultado}")
  end

  def arredonda_nota(nota)
    ('%.1f' % nota) if nota
  end

end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <% if @author.errors.any? %>
    <%= render 'shared/form_errors', form: @author %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h2><%= t('.editar') %></h2>

<%= render 'form' %>

<%= link_to(t('authors.voltar'), authors_path, class: 'btn btn-default') %>

app/views/authors/index.html.erb
<%= render 'shared/flash_messages' %>

<table class="table table-bordered table-hover">
  <thead class="bg-autores">
  	<tr>
  	  <th><%= t('.nome') %></th>
      <th><%= t('.quantidade') %></th>
  	  <th colspan="2">&nbsp;</th>
  	</tr>
  </thead>
  <tbody>
    <% if @authors.any? %>
    	<% @authors.each do |a| %>
    	  <tr>
    	  	<td><%= a.name %></td>
          <td><%= a.books.where(user_id: session[:user_id]).size %></td>
    	  	<td><%= link_to(t('.editar'), edit_author_path(a), class: 'btn btn-warning btn-sm') %></td>
          <td><%= link_to(t('.deletar'), authors_path(a), method: :delete, data: {confirm: t('.confirmacao')}, class: 'btn btn-danger btn-sm' ) %></td>
    	  </tr>
    	<% end %>
    <% else %>
      <tr>
        <td class="text-center" colspan="4"><%= t('.vazio') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to(t('authors.novo'), new_author_path, class: 'btn btn-primary') %>

app/views/authors/new.html.erb
<h2><%= t('authors.novo') %></h2>

<%= render 'form' %>

<%= link_to(t('authors.voltar'), authors_path, class: 'btn btn-default') %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <% if @book.errors.any? %>
    <%= render 'shared/form_errors', form: @book %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    <br/>
  </div>

  <div class="form-group">
    <%= f.label :author_id %>
    <%= f.collection_select :author_id, @authors, :id, :name, {:prompt => t('.selecione') }, class: 'form-control' %>
    <br/>
  </div>

  <div class="form-group">
    <%= f.label :wishlist %> <br/>
    <%= f.radio_button :wishlist, true, checked: true %>
    <%= label :wishlist_true, t('books.sim') %>
    <%= f.radio_button :wishlist, false %>
    <%= label :wishlist_false, t('books.nao') %>
    <br/>
  </div>

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control' %>
    <br/>
  </div>

  <div id="grupoLido" class="form-group">
    <%= f.label :read %><br/>
    <%= f.radio_button :read, true %>
    <%= label :read_true, t('books.sim') %>
    <%= f.radio_button :read, false, checked: true %>
    <%= label :read_false, t('books.nao') %>
    <br/>
  </div>

  <div id="grupoNotas">
    <div class="form-group">
      <%= f.label :grade %>
      <div id="estrelas"></div>
      <br/>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_list_books.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr class="bg-livros">
      <th colspan='5'><%= t('.todos') %></th>
    </tr>
    <tr class="bg-livros">
      <th><%= t('.nome') %></th>
      <th><%= t('.autor') %></th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @all_books.any? %>
      <% @all_books.each do |b| %>
        <tr>
          <td><%= link_to(b.name, b.link, target: '_blank') %></td>
          <td><%= b.author.name %></td>
          <td><%= traduz_resultado(b.wishlist, 'wishlist') %></td>
          <td><%= traduz_resultado(b.read, 'read') %></td>
          <td><%= link_to(t('.editar'), edit_book_path(b), class: 'btn btn-warning btn-sm') %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center" colspan="6"><%= t('.vazio') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search_box.html.erb
<div class="searchBox">
  <%= form_tag books_search_path, method: :get do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], id: 'searchField', class: 'form-control', placeholder: t('.placeholder') %>
      <%= submit_tag t('.buscar'), :name => nil, class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h2><%= t('.editar') %></h2>

<%= render 'form' %>

<%= link_to(t('books.voltar'), books_path, class: 'btn btn-default') %>

app/views/books/index.html.erb
<%= render 'shared/flash_messages' %>

<%= render 'search_box' %>

<%= render 'list_books' %>

<%= link_to(t('books.novo'), new_book_path, class: 'btn btn-primary') %>

app/views/books/new.html.erb
<h2><%= t('books.novo') %></h2>

<%= render 'form' %>

<%= link_to(t('books.voltar'), books_path, class: 'btn btn-default') %>

app/views/books/search.html.erb
<%= render 'shared/flash_messages' %>

<%= render 'search_box' %>

<%= render 'list_books' %>

<%= link_to(t('books.novo'), new_book_path, class: 'btn btn-primary') %>
<%= link_to(t('.todos'), books_path, class: 'btn btn-primary') %>

app/views/dashboard/_tabela_autores.html.erb
<table class="table table-bordered table-hover">
  <thead class="bg-autores">
    <tr>
      <th class="text-center" colspan="2"><%= titulo %></th>
    </tr>
  </thead>
  <tbody>
    <% if colecao.any? %>
      <% colecao.each do |a| %>
        <tr>
          <td class="col-md-8"><%= a.name %></td>
          <td class="col-md-4"><%= a.books.where(user_id: session[:user_id]).size %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center" colspan="2"><%= vazio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if colecao.any? %>
  <%= link_to(t('.ver_autores'), authors_path, class: 'btn btn-primary') %>
<% else %>
  <%= link_to(t('.novo_autor'), new_author_path, class: 'btn btn-primary') %>
<% end %>

app/views/dashboard/_tabela_livros.html.erb
<table class="table table-bordered table-hover">
  <thead class="bg-livros">
    <tr>
      <th class="text-center" colspan="3"><%= titulo %></th>
    </tr>
  </thead>
  <tbody>
    <% if colecao.any? %>
      <% colecao.each do |b| %>
        <tr>
          <td class="col-md-4"><%= link_to(b.name, b.link, target: '_blank') %></td>
          <td class="col-md-4"><%= b.author.name %></td>
          <% if para_compra %>
            <td class="col-md-4 text-center"><%= link_to(t('.comprei'), bought_path(b), class: 'btn btn-default') %></td>
          <% else %>
            <td class="col-md-4"><%= b.grade %></td>
          <% end %>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center" colspan="3"><%= vazio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if colecao.any? %>
  <%= link_to(t('.ver_livros'), books_path, class: 'btn btn-primary') %>
<% else %>
  <%= link_to(t('.novo_livro'), new_book_path, class: 'btn btn-primary') %>
<% end %>

app/views/dashboard/_tabela_livros_comprados.html.erb
<table class="table table-bordered table-hover">
  <thead class="bg-livros">
    <tr>
      <th class="text-center" colspan="2"><%= titulo %></th>
    </tr>
  </thead>
  <tbody>
    <% if colecao.any? %>
      <% colecao.each do |b| %>
        <tr>
          <td class="col-md-4"><%= link_to(b.name, b.link, target: '_blank') %></td>
          <td class="col-md-4"><%= b.author.name %></td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td class="text-center" colspan="2"><%= vazio %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if colecao.any? %>
  <%= link_to(t('.ver_todos'), books_path, class: 'btn btn-primary') %>
<% end %>

app/views/dashboard/index.html.erb
<%= render 'shared/flash_messages' %>

<div class="separaDivs">
  <div class="col-md-6">
    <%= render 'tabela_livros', 
          colecao: @ultimos_adicionados, 
          titulo: t('.ultimos_adicionados'), 
          vazio: t('.ultimos_adicionados_vazios'),
          para_compra: true %>
  </div>

  <div class="col-md-6">
    <%= render 'tabela_livros_comprados', 
          colecao: @livros_comprados, 
          titulo: t('.livros_comprados'), 
          vazio: t('.livros_comprados_vazios'),
          para_compra: false %>
  </div>
</div>

<div class="separaDivs">
  <div class="col-md-6">
    <%= render 'tabela_livros', 
          colecao: @ultimos_lidos,
          titulo: t('.ultimos_lidos'),
          vazio: t('.ultimos_lidos_vazio'),
          para_compra: false %>
  </div>

  <div class="col-md-6">
    <%= render 'tabela_autores', 
          colecao: @ultimos_autores,
          titulo: t('.ultimos_autores'),
          vazio: t('.ultimos_autores_vazio') %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= monta_title %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Prelo" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container <%= " logoHome" unless logged_in? %>">
  <header>
    <h1 <%= "class=logoHome" unless logged_in? %>>
      <%= link_to(t('geral.app_name'), dashboard_path) %>
    </h1>

    <% if logged_in? %>
      <div id="menuTopo">
        <ul <%= "class=isAdmin" if is_admin? %>>
          <li><%= link_to(t('.menu_home'), dashboard_path) %></li>
          <li><%= link_to(t('.menu_autores'), authors_path) %></li>
          <li><%= link_to(t('.menu_livros'), books_path) %></li>
          <% if is_admin? %>
            <li><%= link_to(t('.menu_usuarios'), users_path) %></li>
          <% end %>
          <li><%= link_to(t('.menu_logout'), logout_path) %></li>
        </ul>
      </div>
    <% end %>
  </header>

  <%= yield %>
</div>

<% if logged_in? %>
  <footer>
    <div class="container">
      <ul id="menuRodape">
        <li class="primeiroNivel"><%= link_to(t('.menu_home'), dashboard_path) %></li>
        <li class="primeiroNivel"><%= link_to(t('.menu_autores'), authors_path) %></li>
        <li class="primeiroNivel"><%= link_to(t('.menu_livros'), books_path) %></li>
      </ul>
    </div>
  </footer>
<% end %>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash[:alert] %>
  <div id="alertNotice">
    <p class="bg-warning"><%= flash[:alert] %></p>
  </div>
<% end %>

<% if flash[:success] %>
  <div id="successNotice">
    <p class="bg-success"><%= flash[:success] %></p>
  </div>
<% end %>

<% if flash[:failure] %>
  <div id="errorNotice">
    <p class="bg-danger"><%= flash[:failure] %></p>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<div id="errorNotice">
  <p class="bg-danger">
    <span>Ops!<br/></span>
    <% form.errors.full_messages.each do |msg| %>
      <span><%= msg %></span>
      <br/>
    <% end %>
  </p>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <%= render 'shared/form_errors', form: @user %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :login %>
    <%= f.text_field :login, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2><%= t('.editar') %></h2>

<%= render 'form' %>

<%= link_to(t('users.voltar'), users_path, class: 'btn btn-default') %>

app/views/users/index.html.erb
<%= render 'shared/flash_messages' %>

<table class="table table-bordered table-hover">
  <thead class="bg-usuarios">
    <tr>
      <th><%= t('.nome') %></th>
      <th><%= t('.email') %></th>
      <th><%= t('.usuario') %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= u.name %></td>
        <td><%= u.email %></td>
        <td><%= u.login %></td>
        <td><%= link_to(t('.editar'), edit_user_path(u), class: 'btn btn-warning btn-sm') %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to(t('users.novo'), new_user_path, class: 'btn btn-primary') %>

app/views/users/new.html.erb
<h2><%= t('users.novo') %></h2>

<%= render 'form' %>

<%= link_to(t('users.voltar'), users_path, class: 'btn btn-default') %>